name:
  maximum: 50
email:
  maximum: 255
password:
  minimum: 6
user_helper:
  size: 80
indexpage:
  user_per_page: 10
user:
  index:
    per_page: 10
  expired_time: 2
micropost:
  content:
    max_length: 140
  picture_size: 5
picture:
  limit_size:
    height: 400
users:
  show_follow:
    size: 30
